### ISSUE TITLE
Please, correct copyright attribution

### ISSUE THREAD

**Issue by NightTsarina** [brandond/homeplug_exporter#1]
Hi,

I have prepared a Debian package for the homeplug exporter, but it is being rejected by the ftp-masters, as the LICENSE file assigns copyright to "neezgee", who does not seem to be related to this code at all, and seems like a mistake.

Could you correct that? You just need to change that to your name and email.

Thanks.

**Comment by brandond** [comment]
Whoops! Thanks for using the project, and sorry for the copypasta. I'll fix it this evening.

**Comment by brandond** [comment]
Fixed. Let me know if they need me to tag a new release with the license change.
